 readme file in task python-exceptions
